USE [master]
GO
/****** Object:  Database [Homecenter]    Script Date: 2018-03-13 05.20.40  ******/
CREATE DATABASE [Homecenter] ON  PRIMARY 
( NAME = N'Homecenter', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Homecenter.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Homecenter_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Homecenter_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Homecenter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Homecenter] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Homecenter] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Homecenter] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Homecenter] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Homecenter] SET ARITHABORT OFF 
GO
ALTER DATABASE [Homecenter] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Homecenter] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Homecenter] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Homecenter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Homecenter] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Homecenter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Homecenter] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Homecenter] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Homecenter] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Homecenter] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Homecenter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Homecenter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Homecenter] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Homecenter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Homecenter] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Homecenter] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Homecenter] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Homecenter] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Homecenter] SET  MULTI_USER 
GO
ALTER DATABASE [Homecenter] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Homecenter] SET DB_CHAINING OFF 
GO
